"""delete_conversations

Revision ID: 2a4cbeccc21b
Revises: 0002
Create Date: 2026-05-24 16:11:11.959740
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2a4cbeccc21b'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocoding_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=True),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_hash')
    )
    op.create_index('geocoding_cache_expires_idx', 'geocoding_cache', ['expires_at'], unique=False)
    op.create_index('geocoding_cache_hash_idx', 'geocoding_cache', ['query_hash'], unique=False)
    op.drop_index(op.f('geoapify_cache_expires_idx'), table_name='geoapify_cache')
    op.drop_index(op.f('geoapify_cache_hash_idx'), table_name='geoapify_cache')
    op.drop_table('geoapify_cache')
    op.drop_index(op.f('conversations_landlord_id_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_last_message_at_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_listing_id_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_tenant_id_idx'), table_name='conversations')
    op.drop_table('conversations')
    op.alter_column('featured_listing_purchases', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('listings', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('listings', 'area',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('listings', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('listings', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('listings', 'title_el',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('listings', 'description_el',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_index(op.f('listings_search_el_idx'), table_name='listings', postgresql_using='gin')
    op.create_index('listings_search_el_idx', 'listings', [sa.literal_column("to_tsvector('greek', coalesce(title_el, '') || ' ' || coalesce(description_el, ''))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('listings_search_en_idx'), table_name='listings', postgresql_using='gin')
    op.create_index('listings_search_en_idx', 'listings', [sa.literal_column("to_tsvector('english', coalesce(title_en, '') || ' ' || coalesce(description_en, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('listings_search_en_idx', table_name='listings', postgresql_using='gin')
    op.create_index(op.f('listings_search_en_idx'), 'listings', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(title_en, ''::character varying)::text || ' '::text) || COALESCE(description_en, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('listings_search_el_idx', table_name='listings', postgresql_using='gin')
    op.create_index(op.f('listings_search_el_idx'), 'listings', [sa.literal_column("to_tsvector('greek'::regconfig, (COALESCE(title_el, ''::character varying)::text || ' '::text) || COALESCE(description_el, ''::text))")], unique=False, postgresql_using='gin')
    op.alter_column('listings', 'description_el',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('listings', 'title_el',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('listings', 'longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('listings', 'latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('listings', 'area',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('listings', 'price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('featured_listing_purchases', 'amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('landlord_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], name=op.f('conversations_landlord_id_users_id_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('conversations_listing_id_listings_id_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], name=op.f('conversations_tenant_id_users_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey')),
    sa.UniqueConstraint('listing_id', 'landlord_id', 'tenant_id', name=op.f('conversations_listing_landlord_tenant_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('conversations_tenant_id_idx'), 'conversations', ['tenant_id'], unique=False)
    op.create_index(op.f('conversations_listing_id_idx'), 'conversations', ['listing_id'], unique=False)
    op.create_index(op.f('conversations_last_message_at_idx'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('conversations_landlord_id_idx'), 'conversations', ['landlord_id'], unique=False)
    op.create_table('geoapify_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('lang', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('geoapify_cache_pkey')),
    sa.UniqueConstraint('query_hash', name=op.f('geoapify_cache_query_hash_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('geoapify_cache_hash_idx'), 'geoapify_cache', ['query_hash'], unique=False)
    op.create_index(op.f('geoapify_cache_expires_idx'), 'geoapify_cache', ['expires_at'], unique=False)
    op.drop_index('geocoding_cache_hash_idx', table_name='geocoding_cache')
    op.drop_index('geocoding_cache_expires_idx', table_name='geocoding_cache')
    op.drop_table('geocoding_cache')
    # ### end Alembic commands ###
