"""empty message

Revision ID: 3cb36aaee727
Revises: 1d8a8d2c7092
Create Date: 2026-09-06 20:59:59.433613
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3cb36aaee727'
down_revision: Union[str, None] = '1d8a8d2c7092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
