"""initial schema

Revision ID: 95c2c6236605
Revises: 
Create Date: 2026-09-27 19:47:44.882332
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '95c2c6236605'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocoding_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=True),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_hash')
    )
    op.create_index('geocoding_cache_expires_idx', 'geocoding_cache', ['expires_at'], unique=False)
    op.create_index('geocoding_cache_hash_idx', 'geocoding_cache', ['query_hash'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('LANDLORD', 'TENANT', 'BOTH', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', 'SUSPENDED', name='user_status'), server_default='ACTIVE', nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=50), nullable=True),
    sa.Column('floor', sa.Enum('basement', 'semi-basement', 'ground', '1st', '2nd', '3rd', '4th', '5th', '6th+', name='floors'), server_default='ground', nullable=False),
    sa.Column('levels', sa.Integer(), server_default='1', nullable=False),
    sa.Column('kitchens', sa.Integer(), server_default='1', nullable=False),
    sa.Column('bedrooms', sa.Integer(), server_default='1', nullable=False),
    sa.Column('bathrooms', sa.Integer(), server_default='1', nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('elevator', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('parking_space', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('furnished', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('zone_type', sa.Enum('Residential', 'Agricultural', 'Commercial', 'Industrial', 'Regeneration', name='zone_type'), server_default='Residential', nullable=False),
    sa.Column('listing_status', sa.Enum('Renovated', 'Luxurious', 'Under construction', 'Neoclassical', name='listing_status'), nullable=True),
    sa.Column('publication_status', sa.Enum('DRAFT', 'ACTIVE', name='publication_status'), server_default='ACTIVE', nullable=False),
    sa.Column('date_available', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_built', sa.Integer(), server_default=sa.text('EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER'), nullable=False),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('country', sa.String(length=255), server_default='Greece', nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('property_type', sa.Enum('apartment', 'house', 'studio', 'room', name='property_type'), nullable=False),
    sa.Column('available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('landlord_phone', sa.String(length=20), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verification_status'), server_default='PENDING', nullable=False),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('featured_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('title_el', sa.String(length=100), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=100), nullable=True),
    sa.Column('description_el', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.CheckConstraint('area >= 0', name='area'),
    sa.CheckConstraint('bathrooms >= 0', name='bathrooms'),
    sa.CheckConstraint('bedrooms >= 0', name='bedrooms'),
    sa.CheckConstraint('kitchens >= 0', name='kitchens'),
    sa.CheckConstraint('levels >= 0', name='levels'),
    sa.CheckConstraint('price >= 0', name='price'),
    sa.CheckConstraint('views_count >= 0', name='views_count'),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('listings_area_idx', 'listings', ['area'], unique=False)
    op.create_index('listings_available_featured_idx', 'listings', ['available', 'is_featured'], unique=False)
    op.create_index('listings_available_idx', 'listings', ['available'], unique=False)
    op.create_index('listings_bathrooms_idx', 'listings', ['bathrooms'], unique=False)
    op.create_index('listings_bedrooms_idx', 'listings', ['bedrooms'], unique=False)
    op.create_index('listings_city_idx', 'listings', ['city'], unique=False)
    op.create_index('listings_city_price_idx', 'listings', ['city', 'price'], unique=False)
    op.create_index('listings_country_idx', 'listings', ['country'], unique=False)
    op.create_index('listings_created_at_idx', 'listings', ['created_at'], unique=False)
    op.create_index('listings_featured_until_idx', 'listings', ['featured_until'], unique=False)
    op.create_index('listings_is_featured_idx', 'listings', ['is_featured'], unique=False)
    op.create_index('listings_landlord_id_idx', 'listings', ['landlord_id'], unique=False)
    op.create_index('listings_price_idx', 'listings', ['price'], unique=False)
    op.create_index('listings_property_type_idx', 'listings', ['property_type'], unique=False)
    op.create_index('listings_publication_status_idx', 'listings', ['publication_status'], unique=False)
    op.create_index('listings_type_city_idx', 'listings', ['property_type', 'city'], unique=False)
    op.create_index('listings_verification_status_idx', 'listings', ['verification_status'], unique=False)
    op.create_index(
        'listings_search_en_idx',
        'listings',
        [sa.text("to_tsvector('english', coalesce(title_en, '') || ' ' || coalesce(description_en, ''))")],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'listings_search_el_idx',
        'listings',
        [sa.text("to_tsvector('greek', coalesce(title_el, '') || ' ' || coalesce(description_el, ''))")],
        unique=False,
        postgresql_using='gin',
    )
    op.create_table('availability_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('availability_slots_is_booked_idx', 'availability_slots', ['is_booked'], unique=False)
    op.create_index('availability_slots_landlord_id_idx', 'availability_slots', ['landlord_id'], unique=False)
    op.create_index('availability_slots_listing_id_idx', 'availability_slots', ['listing_id'], unique=False)
    op.create_index('availability_slots_start_time_idx', 'availability_slots', ['start_time'], unique=False)
    op.create_table('featured_listing_purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('purchased_by', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='featured_purchase_status'), server_default='PENDING', nullable=False),
    sa.Column('starts_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchased_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('featured_purchases_expires_at_idx', 'featured_listing_purchases', ['expires_at'], unique=False)
    op.create_index('featured_purchases_listing_id_idx', 'featured_listing_purchases', ['listing_id'], unique=False)
    op.create_index('featured_purchases_status_idx', 'featured_listing_purchases', ['status'], unique=False)
    op.create_table('interested_listings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'listing_id')
    )
    op.create_table('listing_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('UTILITY_BILL', 'TITLE_DEED', 'LEASE_AGREEMENT', 'PROPERTY_TAX', 'OTHER', name='document_type'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('verification_docs_listing_id_idx', 'verification_documents', ['listing_id'], unique=False)
    op.create_table('verification_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verification_status'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('verification_history_listing_id_idx', 'verification_history', ['listing_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DECLINED', 'CANCELLED', name='booking_status'), server_default='PENDING', nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('meet_link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('availability_slot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['availability_slot_id'], ['availability_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('bookings_availability_slot_id_idx', 'bookings', ['availability_slot_id'], unique=False)
    op.create_index('bookings_candidate_id_idx', 'bookings', ['candidate_id'], unique=False)
    op.create_index('bookings_landlord_id_idx', 'bookings', ['landlord_id'], unique=False)
    op.create_index('bookings_listing_id_idx', 'bookings', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bookings_listing_id_idx', table_name='bookings')
    op.drop_index('bookings_landlord_id_idx', table_name='bookings')
    op.drop_index('bookings_candidate_id_idx', table_name='bookings')
    op.drop_index('bookings_availability_slot_id_idx', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('verification_history_listing_id_idx', table_name='verification_history')
    op.drop_table('verification_history')
    op.drop_index('verification_docs_listing_id_idx', table_name='verification_documents')
    op.drop_table('verification_documents')
    op.drop_table('listing_images')
    op.drop_table('interested_listings')
    op.drop_index('featured_purchases_status_idx', table_name='featured_listing_purchases')
    op.drop_index('featured_purchases_listing_id_idx', table_name='featured_listing_purchases')
    op.drop_index('featured_purchases_expires_at_idx', table_name='featured_listing_purchases')
    op.drop_table('featured_listing_purchases')
    op.drop_index('availability_slots_start_time_idx', table_name='availability_slots')
    op.drop_index('availability_slots_listing_id_idx', table_name='availability_slots')
    op.drop_index('availability_slots_landlord_id_idx', table_name='availability_slots')
    op.drop_index('availability_slots_is_booked_idx', table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_index('listings_verification_status_idx', table_name='listings')
    op.drop_index('listings_type_city_idx', table_name='listings')
    op.drop_index('listings_publication_status_idx', table_name='listings')
    op.drop_index('listings_property_type_idx', table_name='listings')
    op.drop_index('listings_price_idx', table_name='listings')
    op.drop_index('listings_landlord_id_idx', table_name='listings')
    op.drop_index('listings_is_featured_idx', table_name='listings')
    op.drop_index('listings_featured_until_idx', table_name='listings')
    op.drop_index('listings_created_at_idx', table_name='listings')
    op.drop_index('listings_country_idx', table_name='listings')
    op.drop_index('listings_city_price_idx', table_name='listings')
    op.drop_index('listings_city_idx', table_name='listings')
    op.drop_index('listings_bedrooms_idx', table_name='listings')
    op.drop_index('listings_bathrooms_idx', table_name='listings')
    op.drop_index('listings_available_idx', table_name='listings')
    op.drop_index('listings_available_featured_idx', table_name='listings')
    op.drop_index('listings_area_idx', table_name='listings')
    op.drop_index('listings_search_el_idx', table_name='listings', postgresql_using='gin')
    op.drop_index('listings_search_en_idx', table_name='listings', postgresql_using='gin')
    op.drop_table('listings')
    op.drop_table('users')
    op.drop_index('geocoding_cache_hash_idx', table_name='geocoding_cache')
    op.drop_index('geocoding_cache_expires_idx', table_name='geocoding_cache')
    op.drop_table('geocoding_cache')
    op.execute("DROP TYPE IF EXISTS booking_status")
    op.execute("DROP TYPE IF EXISTS document_type")
    op.execute("DROP TYPE IF EXISTS featured_purchase_status")
    op.execute("DROP TYPE IF EXISTS verification_status")
    op.execute("DROP TYPE IF EXISTS property_type")
    op.execute("DROP TYPE IF EXISTS publication_status")
    op.execute("DROP TYPE IF EXISTS listing_status")
    op.execute("DROP TYPE IF EXISTS zone_type")
    op.execute("DROP TYPE IF EXISTS floors")
    op.execute("DROP TYPE IF EXISTS user_status")
    op.execute("DROP TYPE IF EXISTS user_role")
    # ### end Alembic commands ###
