"""empty message

Revision ID: d41c6499bca5
Revises: 1ae397f6771e
Create Date: 2026-09-26 22:00:07.707839
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd41c6499bca5'
down_revision: Union[str, None] = '1ae397f6771e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


auth_provider_enum = postgresql.ENUM('EMAIL', 'GOOGLE', name='auth_provider', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    auth_provider_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_provider', auth_provider_enum, server_default='EMAIL', nullable=False))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('LANDLORD', 'TENANT', 'BOTH', 'ADMIN', name='user_role'),
               nullable=False)
    op.drop_constraint(op.f('users_clerk_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_clerk_id_key'), 'users', ['clerk_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('LANDLORD', 'TENANT', 'BOTH', 'ADMIN', name='user_role'),
               nullable=True)
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'auth_provider')
    auth_provider_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
