"""update_descriptions

Revision ID: f1d6be256126
Revises: 2a4cbeccc21b
Create Date: 2026-05-24 17:40:31.854649
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f1d6be256126'
down_revision: Union[str, None] = '2a4cbeccc21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('listings_search_el_idx'), table_name='listings', postgresql_using='gin')
    op.create_index('listings_search_el_idx', 'listings', [sa.literal_column("to_tsvector('greek', coalesce(title_el, '') || ' ' || coalesce(description_el, ''))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('listings_search_en_idx'), table_name='listings', postgresql_using='gin')
    op.create_index('listings_search_en_idx', 'listings', [sa.literal_column("to_tsvector('english', coalesce(title_en, '') || ' ' || coalesce(description_en, ''))")], unique=False, postgresql_using='gin')
    op.drop_column('listings', 'description')
    op.drop_column('listings', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index('listings_search_en_idx', table_name='listings', postgresql_using='gin')
    op.create_index(op.f('listings_search_en_idx'), 'listings', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(title_en, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('listings_search_el_idx', table_name='listings', postgresql_using='gin')
    op.create_index(op.f('listings_search_el_idx'), 'listings', [sa.literal_column("to_tsvector('greek'::regconfig, (COALESCE(title_el, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
